spring.application.name=DormlyBackend

server.port=8080

spring.datasource.url=jdbc:sqlserver://${DB_SERVER:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:dormly};encrypt=false;trustServerCertificate=true;sendTimeAsDateTime=false
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:12345678}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


app.redis.host=localhost
app.redis.port=6379
app.redis.username=
app.redis.password=


# ===== Tracing sampling =====
management.tracing.sampling.probability=1.0

# ===== Zipkin endpoint =====
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# ===== Logging pattern =====
logging.pattern.console=%d{HH:mm:ss} [%X{traceId}] [%X{spanId}] %-5level %logger{36} - %msg%n

app.jwt.secret=b7f3c2d91a4e8f6b5c7d2e1f9a0b3c4d8e6f1a2b5c7d9e0f3a1b4c6d8e9f0a2
app.jwt.expiration-ms=900000
app.jwt.refresh-expiration-ms=604800000

#spring.security.require-ssl=true

# Fix invalid path pattern errors with swagger-ui assets on Spring Boot 3.5
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# Temporarily disable swagger-ui to avoid invalid mapping pattern on Spring Boot 3.5
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.persist-authorization= true

